### ISSUE TITLE
Make server core module with pure functions

### ISSUE THREAD

**Issue by eugrdn** [eugrdn/vote-it#2]

**Comment by prabodh1194** [comment]
I guess we can use some more description:

- Vote and revote are 'impure' functions
- initState and initTopics are pure functions only

Am I correct?

**Comment by eugrdn** [comment]
@prabodh1194 yes, you are right

**Comment by prabodh1194** [comment]
So we need to rewrite vote() and revote()

**Comment by eugrdn** [comment]
Yes, they shouldn't mutate the state

**Comment by prabodh1194** [comment]
hmm. let's see if I get any ideas

**Comment by prabodh1194** [comment]
One idea I have is let vote() function return a sort of set of instructions for 'state'  which can be merged into 'state'.

Also, what is the motivation for having pure function? Any particular reason?

**Comment by eugrdn** [comment]
Motivation is that we are using _redux_ to manage the state. I think you need to investigate client reducer, and implement the same approach on server.

**Comment by eugrdn** [comment]
Closed with #17
