### ISSUE TITLE
Use MongoDB for data storage

### ISSUE THREAD

**Issue by eugrdn** [eugrdn/vote-it#4]

**Comment by Jp3rd** [comment]
You mean a local MongoDB right?

**Comment by eugrdn** [comment]
Yes, but you also could use something like https://mlab.com/

**Comment by abdullateef97** [comment]
pls reply if stil open

**Comment by eugrdn** [comment]
@abdullateef97 it is still open :)

**Comment by abdullateef97** [comment]
okay
can u please explain the project structure
where is the onclick method handled and the likes

**Comment by eugrdn** [comment]
Do you consider, this is hard to understand from the code base?

**Comment by abdullateef97** [comment]
do u agree with that

**Comment by eugrdn** [comment]
it already has backend part
